name: UX Brighton
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true
exclude: [CNAME]
plugins:
  - jekyll-redirect-from
sass:
  style: compressed
  sass_dir: ./2022/stylesheets/scss
