backend:
  name: github
  repo: dannyhope/uxbrighton # Path to the GitHub code repository
  branch: gh-pages # Branch that Netlify CMS will be available on
  site_domain: uxbri-netlify-cms.netlify.com # Using a placeholder Netlify site and custom Netlify domain to enable the backend OAuth configuration

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']

# These lines should *not* be indented
publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with images/uploads
site_url: https://uxbri.org/
display_url: https://uxbri.org/
logo_url: https://uxbri.org/2022/logo/red-square-small.png

collections:
  - label: "UX Brighton 2022"
    name: "uxbri-2022"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "2022/index.html"
        fields:
          - {label: "Title", name: "title", hint: "Primary title of the page.", widget: "string"}
          - {label: "Description", name: "description", hint: "This is *meta* content. Beneficial to SEO.", widget: "string"}
          - {label: "Page URL", name: "fullurl", hint: "This is *meta* content. Social channels & SEO.", widget: "string", default: "https://uxbri.org/2022/"}
          - label: "Hero" # Hero section
            hint: "Hero (top) section of the website."
            name: "hero"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Hero Background Image", name: "hero-image", widget: "string", default: "/2022/images/header.jpg"} # Hero background image
              - label: "Button" # Button (primary)
                name: "button"
                widget: "object"
                collapsed: true
                fields:
                  - {label: "Button visibility", name: "ticket-button", hint: "Choose whether to *show* or *hide* the ticket button. It defaults to *show*.", widget: "select", options: ["show", "hide"], default: ["show"]}
                  - {label: "Button text", name: "ticket-button-text", hint: "Text in the button.", widget: "string"}
                  - {label: "Button text - extra", name: "ticket-button-extra-text", hint: "This text appears just below the button.", widget: "string", required: false}
                  - {label: "Button URL Address", name: "ticket-button-url", hint: "URL this button points to.", widget: "string"}
